language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX="g++-4.8"
node_js:
  - "4.1.0"
  - "4.0.0"
  - "0.12"
  - "0.10"
os:
  - linux
